export const TYPES = {
    TOGGLE_MODAL_TO_REGISTER_TANK: 'TOGGLE_MODAL_TO_REGISTER_TANK',
    REGISTER_TANK: 'REGISTER_TANK',
    ASSIGN_TANK_TO_VESSEL: 'ASSIGN_TANK_TO_VESSEL',
    TOGGLE_MODAL_TO_ASSIGN_TANK_TO_VESSEL: 'TOGGLE_MODAL_TO_ASSIGN_TANK_TO_VESSEL',
    SELECT_TANK: 'SELECT_TANK',
    SELECT_VESSEL: 'SELECT_VESSEL'
}