export const TYPES = {
    TOGGLE_MODAL_TO_REGISTER_TANK: 'TOGGLE_MODAL_TO_REGISTER_TANK',
    REGISTER_TANK: 'REGISTER_TANK',
    SELECT_CYLINDER_SIZE: 'SELECT_CYLINDER_SIZE',
    POPOULATE_VESSEL_GRID_TANKS: 'POPOULATE_VESSEL_GRID_TANKS'
}