export const TYPES = {
    TOGGLE_MODAL_TO_REGISTER_TANK: 'TOGGLE_MODAL_TO_REGISTER_TANK',
    REGISTER_TANK: 'REGISTER_TANK',
    ASSIGN_TANK_TO_VESSEL: 'ASSIGN_TANK_TO_VESSEL',
    TOGGLE_MODAL_TO_ASSIGN_TANK_TO_VESSEL: 'TOGGLE_MODAL_TO_ASSIGN_TANK_TO_VESSEL',
    SELECTED_TANK: 'SELECTED_TANK',
    SELECT_FROM_VESSEL_LIST: 'SELECT_FROM_VESSEL_LIST'
}